controller_list:
  # - name: ALL_controller
  #   action_ns: follow_joint_trajectory
  #   default: True
  #   type: FollowJointTrajectory
  #   joints:
  #     - shoulder_pan_joint
  #     - shoulder_lift_joint
  #     - elbow_joint
  #     - wrist_1_joint
  #     - wrist_2_joint
  #     - wrist_3_joint
  #     - gripper_finger1_joint
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      gripper_finger1_joint
